version: 3.9.1.{build}
shallow_clone: true
skip_branch_with_pr: false
skip_commits:
  message: /!nobuild/
skip_tags: false

environment:
  access_token_documentation:
    secure: JVBVVL8uJUcLXN+48eRdELEeCGOGCCaMzCqutsUqNuaZ/KblG5ZTt7+LV4UKv/0f
  LUAROCKS_VER: 2.4.1
  LUA_VER: 5.1.5
  LUA: lua5.3
  matrix:
  - LUA_VER: 5.1.5

platform:
  - x64

init:
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
# Outcomment if lua environment invalidates and needs to be reinstalled, otherwise all will run from the cache.
#  - call choco install 7zip.commandline
#  - call choco install lua51
#  - call choco install luarocks
#  - call refreshenv
#  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - cmd: PATH = %PATH%;C:\ProgramData\chocolatey\lib\luarocks\luarocks-2.4.3-win32\systree\bin
  - cmd: set LUA_PATH = %LUA_PATH%;C:\ProgramData\chocolatey\lib\luarocks\luarocks-2.4.3-win32\systree\share\lua\5.1\?.lua;C:\ProgramData\chocolatey\lib\luarocks\luarocks-2.4.3-win32\systree\share\lua\5.1\?\init.lua
  - cmd: set LUA_CPATH = %LUA_CPATH%;C:\ProgramData\chocolatey\lib\luarocks\luarocks-2.4.3-win32\systree\lib\lua\5.1\?.dll 
#  - call luarocks install luasrcdiet
#  - call luarocks install checks
#  - call luarocks install luadocumentor
#  - call luarocks install luacheck


cache:
  - C:\ProgramData\chocolatey\lib
  - C:\ProgramData\chocolatey\bin
  


build_script:
   - cmd: md "Moose_Include_Static"
   - cmd: md "Moose_Include_Dynamic"
   - call lua5.1 "Moose Setup\\Moose_Create.lua" "S" %APPVEYOR_REPO_COMMIT% "Moose Development\\Moose" "Moose Setup" "Moose_Include_Static" 
   - call lua5.1 "Moose Setup\\Moose_Create.lua" "D" %APPVEYOR_REPO_COMMIT% "Moose Development\\Moose" "Moose Setup" "Moose_Include_Dynamic"
   - call luasrcdiet --basic --opt-emptylines "Moose_Include_Static\Moose.lua"
   - ps: | 
       if( $env:appveyor_repo_branch -eq 'master' )     
       {
         $apiUrl = 'https://ci.appveyor.com/api'
         $token = 'qts80b5kpq0ooj4x6vvw'
         $headers = @{
           "Authorization" = "Bearer $token"
           "Content-type" = "application/json"
           }
         $RequestBody = @{ accountName = 'FlightControl-Master'; projectSlug = 'moose-docs'; branch = 'master'; environmentVariables = @{} } | ConvertTo-Json
         # get project with last build details
         $project = Invoke-RestMethod -method Post -Uri "$apiUrl/builds" -Headers $headers -Body $RequestBody
       }
   - ps: |
       if( $env:appveyor_repo_branch -eq 'master' )     
       {
         git clone -q https://github.com/FlightControl-Master/MOOSE_INCLUDE.git c:\Projects\Moose_Include
         md c:\Projects\Moose_Include\Moose_Include_Static
         md c:\Projects\Moose_Include\Moose_Include_Dynamic
         cp Moose_Include_Static\*.lua c:\Projects\Moose_Include\Moose_Include_Static
         cp Moose_Include_Dynamic\*.lua c:\Projects\Moose_Include\Moose_Include_Dynamic
         cd c:\Projects\Moose_Include
         dir
         echo "Commit the Moose.lua include files to the MOOSE_INCLUDE repository"
         git config --global credential.helper store  
         Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token_documentation):x-oauth-basic@github.com`n" 
         git config --global user.email "sven.van.de.velde@telenet.be" 
         git config --global user.name "FlightControl-User" 
         git add .
         git commit -m "MOOSE Commit Hash ID $env:APPVEYOR_REPO_COMMIT [skip ci]" 2>&1 
         git push origin master 2>&1
         dir
       }


#   ps : >- 
#       if( $env:appveyor_repo_branch -eq 'master' )     
#       {  
#         . .av\build_missions.bat
#       }

test: off
# test_script:
#   - cmd: luacheck "Moose Development\Moose\moose.lua" "Moose Mission Setup\moose.lua"


artifacts:
  - path: 'Moose_Include_Static\*.lua'
    name: Static
  - path: 'Moose_Include_Dynamic\*.lua'
    name: Dynamic
#  - path: 'MOOSE_MISSIONS-Release\*.miz'
#    name: miz

on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
