settings=
{
	["delta_mode"]=0,
	["disp_tapes"]=0,
	["mnt_boresight_up"]=0,
	["30mm_pac1_pos"]=1,
	["mnt_boresight"]=0,
	["rty_wngspn"]=1,
	["var_tgt_elev"]=0,
	["30mm_rnds"]=6029412,
	["disp_vertvel"]=0,
	["30mm_min_alt"]=1.2461187723206e-306,
	["offadj_enabled"]=1,
	["disp_autodata"]=0,
	["disp_rdralt"]=0,
	["aas_threats"]=
	{
		[1]=
		{
			["in_rotary"]=1,
		},
		[2]=
		{
			["in_rotary"]=1,
		},
		[3]=
		{
			["in_rotary"]=0,
		},
		[4]=
		{
			["in_rotary"]=0,
		},
		[5]=
		{
			["in_rotary"]=0,
		},
		[6]=
		{
			["in_rotary"]=0,
		},
		[7]=
		{
			["in_rotary"]=1,
		},
		[8]=
		{
			["in_rotary"]=1,
		},
		[9]=
		{
			["in_rotary"]=0,
		},
		[10]=
		{
			["in_rotary"]=0,
		},
	},
	["ccip_consent_opt"]=0,
	["gcas_plane"]=458980,
	["30mm_ammo_type"]=6488169,
	["rty_tgtspeed"]=10,
	["delta_msl_cal"]=0,
	["delta_gps_msl"]=0,
	["rty_length"]=1,
	["disp_ccip_cross"]=1,
	["wpn_rel_scroll"]=0,
	["gcas_scroll"]=0,
	["gcas_training_opt"]=0,
	["delta_gps_alt"]=0,
	["delta_rdr_alt"]=0,
	["mnt_boresight_rt"]=0,
	["mode_4"]=
	{
		["mode_active"]=0,
		["mode_interval"]=0,
		["mode_start"]=0,
	},
	["mode_1"]=
	{
		["mode_active"]=0,
		["mode_interval"]=0,
		["mode_start"]=0,
	},
	["bit_flight"]=0,
	["offadj_gun_up"]=0,
	["fxd_tgtspeed"]=10,
	["disp_airspeed"]=0,
	["offadj_bomb_up"]=0,
	["fxd_wngspn"]=1,
	["offadj_bomb_rt"]=0,
	["fxd_length"]=1,
	["disp_metric"]=0,
	["bit_opt"]=0,
	["offadj_gun_rt"]=0,
	["bit_clear"]=0,
	["30mm_ammo_mfg"]=6029427,
}
