version: "3.5"

services:
  jekyll:
    build:
      context: ./
    image: moose/docs
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t --force_polling
