env.info( '*** MOOSE DYNAMIC INCLUDE START *** ' )
env.info( 'Moose Generation Timestamp: 20171122_0612' )

local base = _G

MOOSE = {}

MOOSE.Include = function( LuaPath, IncludeFile )
	if not MOOSE.Includes[ IncludeFile ] then
		MOOSE.Includes[IncludeFile] = IncludeFile
		local f = assert( base.loadfile( LuaPath .. IncludeFile ) )
		if f == nil then
			error ("MOOSE: Could not load Moose file " .. IncludeFile )
		else
			env.info( "MOOSE: " .. IncludeFile .. " dynamically loaded from " .. LuaPath )
			return f()
		end
	end
end

MOOSE.ProgramPath = "Scripts/Moose/"

MOOSE.Includes = {}
MOOSE.Include( MOOSE.ProgramPath, 'Utilities/Routines.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Utilities/Utils.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Base.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/UserFlag.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/UserSound.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Report.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Scheduler.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/ScheduleDispatcher.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Event.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Settings.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Menu.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Zone.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Database.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Set.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Point.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Velocity.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Message.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Fsm.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Radio.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Spawn.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/SpawnStatic.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Goal.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Cargo.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Core/Spot.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Wrapper/Object.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Wrapper/Identifiable.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Wrapper/Positionable.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Wrapper/Controllable.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Wrapper/Group.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Wrapper/Unit.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Wrapper/Client.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Wrapper/Static.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Wrapper/Airbase.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Wrapper/Scenery.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Functional/Scoring.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Functional/CleanUp.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Functional/Movement.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Functional/Sead.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Functional/Escort.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Functional/MissileTrainer.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Functional/ATC_Ground.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Functional/Detection.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Functional/Designate.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Functional/RAT.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Functional/ZoneGoal.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Functional/ZoneGoalCoalition.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Functional/ZoneCaptureCoalition.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'AI/AI_Balancer.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'AI/AI_A2A.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'AI/AI_A2A_Patrol.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'AI/AI_A2A_Cap.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'AI/AI_A2A_Gci.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'AI/AI_A2A_Dispatcher.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'AI/AI_Patrol.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'AI/AI_Cap.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'AI/AI_Cas.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'AI/AI_Bai.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'AI/AI_Formation.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Actions/Act_Assign.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Actions/Act_Route.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Actions/Act_Account.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Actions/Act_Assist.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Tasking/CommandCenter.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Tasking/Mission.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Tasking/Task.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Tasking/DetectionManager.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Tasking/Task_A2G_Dispatcher.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Tasking/Task_A2G.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Tasking/Task_A2A_Dispatcher.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Tasking/Task_A2A.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Tasking/Task_Cargo.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Tasking/TaskZoneCapture.lua' )
MOOSE.Include( MOOSE.ProgramPath, 'Moose.lua' )
BASE:TraceOnOff( true )
env.info( '*** MOOSE INCLUDE END *** ' )
